# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
unbind s
bind | split-window -h
bind v split-window -h
bind - split-window -v
bind s split-window -v
unbind '"'
unbind %

# resize panes with vim bindings
bind-key J resize-pane -D 20
bind-key K resize-pane -U 20
bind-key H resize-pane -L 20
bind-key L resize-pane -R 20

# Shift arrow to switch windows without prefix
bind -n S-Left previous-window
bind -n S-Right next-window

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Enable mouse scroll support
set -g mouse on

# bind [ swap-window -t -1; select-window -t -1
# bind ] swap-window -t +1; select-window -t +1

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf

set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# 0 is too far from `
set -g base-index 1
setw -g monitor-activity on

# fix escape delay from insert mode in nvim
set -sg escape-time 0

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# copy mode
setw -g mode-keys vi

source ~/.config/tmux/theme.conf
source ~/.config/tmux/utility.conf

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

run '~/.tmux/plugins/tpm/tpm'

