# Display lazygit
bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit

# sesh fzf
bind-key T run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 80%,80% \
		--no-sort --border-label ' sesh ' --prompt '   ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(   )+reload(sesh list)'
)\""

# Run Claude Code in a separate session
bind -r y run-shell '\
  SESSION="claude-$(echo #{pane_current_path} | md5sum | cut -c1-8)"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "claude"; \
  tmux display-popup -w80% -h80% -E "tmux attach-session -t $SESSION"'
