"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  type = 'os'
  style = 'plain'
  foreground = 'p:os'
  template = ' {{.Icon}} '

  [[blocks.segments]]
  type = 'root'
  style = 'plain'
  foreground = 'p:yellow'
  template = ' '

  [[blocks.segments]]
  type = 'session'
  style = 'plain'
  foreground = 'p:blue'
  template = '{{ .UserName }} '

  [[blocks.segments]]
  type = "python"
  style = 'plain'
  foreground = 'p:lavender'
  template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}({{ .Venv }}) {{ end }}{{ .Full }}{{ end }} "

  [[blocks.segments]]
  type = 'path'
  style = 'plain'
  foreground = 'p:pink'
  template = '{{ .Path }} '

    [blocks.segments.properties]
    folder_icon = ''
    home_icon = '~'
    style = 'full'

      [blocks.segments.properties.mapped_locations]
      "~/dotfiles/" = "~/"
      "~/dotfiles/.config/nvim/" = "~//"
      "~/.config/nvim/" = "~//"

  [[blocks.segments]]
  type = 'git'
  style = 'plain'
  foreground = 'p:lavender'
  templates = [
    '{{ .UpstreamIcon }}{{ .HEAD }} ',
    '{{ if or (gt .Ahead 0) (gt .Behind 0) }}{{ .BranchStatus }} {{ end }}',
    '{{ if .Working.Changed }}{{ .Working.String }} {{ end }}',
    '{{ if or (and .Working.Changed .Staging.Changed) (gt .StashCount 0) }}| {{ end }}',
    '{{ if gt .Staging.Added 0 }}<p:teal> {{ .Staging.String }}</> {{ end }}',
    '{{ if gt .StashCount 0 }}<p:sapphire> {{ .StashCount }}</> {{ end }}',
  ]

    [blocks.segments.properties]
    branch_icon = ' '
    cherry_pick_icon = ' '
    commit_icon = ' '
    fetch_status = true
    fetch_upstream_icon = false
    merge_icon = ' '
    no_commits_icon = ' '
    rebase_icon = ' '
    revert_icon = ' '
    tag_icon = ' '

      [blocks.segments.properties.status_formats]
      Added = '<p:green>%d</> '
      Deleted = '<p:red>󰧧%d</> '
      Modified = '<p:peach> %d</> '
      Untracked = '<p:yellow>%d</> '
      Unmerged = '<p:yellow>%d</> '

[[blocks]]
type = 'prompt'
alignment = 'left'

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  foreground_templates = [
    '{{if gt .Code 0}}p:red{{end}}',
    '{{if eq .Code 0}}p:blue{{end}}',
  ]
  background = 'transparent'
  template = ''

[transient_prompt]
foreground_templates = [
  '{{if gt .Code 0}}p:red{{end}}',
  '{{if eq .Code 0}}p:blue{{end}}',
]
background = 'transparent'
template = ' '

[secondary_prompt]
foreground = 'p:blue'
background = 'transparent'
template = ' '

[[blocks]]
alignment = 'right'
type = 'rprompt'

  [[blocks.segments]]
  type = 'node'
  style = 'plain'
  foreground = 'p:green'
  background = 'transparent'
  template = ' '

    [blocks.segments.properties]
    display_mode = 'files'
    fetch_package_manager = false
    home_enabled = false

  [[blocks.segments]]
  type = 'angular'
  style = 'plain'
  foreground = 'p:red'
  background = 'transparent'
  template = ' '

  [[blocks.segments]]
  type = 'dotnet'
  style = 'plain'
  foreground = 'p:blue'
  background = 'transparent'
  template = ' '

  [[blocks.segments]]
  type = 'go'
  style = 'plain'
  foreground = 'p:blue'
  background = 'transparent'
  template = ' '

    [blocks.segments.properties]
    fetch_version = false

  [[blocks.segments]]
  type = 'python'
  style = 'plain'
  foreground = 'p:yellow'
  background = 'transparent'
  template = ' '

    [blocks.segments.properties]
    display_mode = 'files'
    fetch_version = false
    fetch_virtual_env = false

  [[blocks.segments]]
  type = 'lua'
  style = 'plain'
  foreground = 'p:blue'
  background = 'transparent'
  template = ' '

  [[blocks.segments]]
  type = 'docker'
  style = 'plain'
  foreground = 'p:blue'
  background = 'transparent'
  template = ' '

  [[blocks.segments]]
  type = 'shell'
  style = 'plain'
  foreground = 'p:text'
  background = 'transparent'
  template = 'in <p:blue><b>{{ .Name }}</b></> '

  [[blocks.segments]]
  type = 'time'
  style = 'plain'
  foreground = 'p:blue'

    [blocks.segments.properties]
    time_format = "15:04:05"


[palette]
blue = '#8AADF4'
lavender = '#B7BDF8'
os = '#ACB0BE'
pink = '#F5BDE6'
peach = '#F5A97F'
rosewater = '#F4DBD6'
flamingo = '#F0C6C6'
mauve = '#C6A0F6'
red = '#ED8796'
maroon = '#EE99A0'
yellow = '#EED49F'
green = '#A6DA95'
teal = '#8BD5CA'
sky = '#91D7E3'
sapphire = '#7DC4E4'
text = '#CAD3F5'
subtext1 = '#B8C0E0'
subtext0 = '#A5ADCB'
overlay2 = '#939AB7'
overlay1 = '#8087A2'
overlay0 = '#6E738D'
surface2 = '#5B6078'
surface1 = '#494D64'
surface0 = '#363A4F'
base = '#24273A'
mantle = '#1E2030'
crust = '#181926'
